server:
  port: 9004

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/baizhanshi/spring-cloud/     # 配置git仓库的地址
          search-paths: config-files                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                   # git仓库的账号
          password:                                 # git仓库的密码
  application:
      name: spring-cloud-config


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/   ## 注册中心eurka地址  实现配置文件的高可用


management:
  security:
     enabled: false
